feat: update dracut to 103-1

diff --git a/test/run-qemu b/test/run-qemu
--- a/test/run-qemu
+++ b/test/run-qemu
@@ -1,41 +1,81 @@
 #!/bin/bash
 # Check which virtualization technology to use
 # We prefer kvm, kqemu, userspace in that order.
-export PATH=/sbin:/bin:/usr/sbin:/usr/bin
 
-[[ -x /usr/bin/qemu ]] && BIN=/usr/bin/qemu && ARGS="-cpu max"
-$(lsmod | grep -q '^kqemu ') && BIN=/usr/bin/qemu && ARGS="-kernel-kqemu -cpu host"
-[[ -c /dev/kvm && -x /usr/bin/kvm ]] && BIN=/usr/bin/kvm && ARGS="-cpu host"
-[[ -c /dev/kvm && -x /usr/bin/qemu-kvm ]] && BIN=/usr/bin/qemu-kvm && ARGS="-cpu host"
-[[ -c /dev/kvm && -x /usr/libexec/qemu-kvm ]] && BIN=/usr/libexec/qemu-kvm && ARGS="-cpu host"
-[[ -x /usr/bin/qemu-system-$(uname -i) ]] && BIN=/usr/bin/qemu-system-$(uname -i) && ARGS="-cpu max"
-[[ -c /dev/kvm && -x /usr/bin/qemu-system-$(uname -i) ]] && BIN=/usr/bin/qemu-system-$(uname -i) && ARGS="-enable-kvm -cpu host"
+export PATH=/usr/sbin:/usr/bin:/sbin:/bin
+ARCH="${ARCH-$(uname -m)}"
+QEMU_CPU="${QEMU_CPU:-max}"
+
+[[ -x /usr/bin/qemu ]] && BIN=/usr/bin/qemu && ARGS=(-cpu "$QEMU_CPU")
+(lsmod | grep -q '^kqemu ') && BIN=/usr/bin/qemu && ARGS=(-kernel-kqemu -cpu host)
+[[ -z ${NO_KVM-} && -c /dev/kvm && -x /usr/bin/kvm ]] && BIN=/usr/bin/kvm && ARGS=(-cpu host)
+[[ -z ${NO_KVM-} && -c /dev/kvm && -x /usr/bin/qemu-kvm ]] && BIN=/usr/bin/qemu-kvm && ARGS=(-cpu host)
+[[ -z ${NO_KVM-} && -c /dev/kvm && -x /usr/libexec/qemu-kvm ]] && BIN=/usr/libexec/qemu-kvm && ARGS=(-cpu host)
+[[ -x "/usr/bin/qemu-system-${ARCH}" ]] && BIN="/usr/bin/qemu-system-${ARCH}" && ARGS=(-cpu "$QEMU_CPU")
+[[ -z ${NO_KVM-} && -c /dev/kvm && -x "/usr/bin/qemu-system-${ARCH}" ]] && BIN="/usr/bin/qemu-system-${ARCH}" && ARGS=(-enable-kvm -cpu host)
 
 [[ $BIN ]] || {
-   echo "Could not find a working KVM or QEMU to test with!" >&2
-   echo "Please install kvm or qemu." >&2
-   exit 1
+    echo "Could not find a working KVM or QEMU to test with!" >&2
+    echo "Please install kvm or qemu." >&2
+    exit 1
 }
 
-# Provide rng device sourcing the hosts /dev/urandom and other standard parameters
-ARGS="$ARGS -smp 2 -m 512 -nodefaults -vga none -display none -no-reboot -device virtio-rng-pci"
+case "$ARCH" in
+    aarch64 | arm64)
+        ARGS+=(-M "virt,gic-version=max")
+        ;;
+    amd64 | i?86 | x86_64)
+        ARGS+=(-M q35)
+        ;;
+    arm | armhf | armv7l)
+        ARGS+=(-M virt)
+        ;;
+    ppc64el | ppc64le)
+        ARGS+=(-M "cap-ccf-assist=off,cap-cfpc=broken,cap-ibs=broken,cap-sbbc=broken")
+        ;;
+esac
 
-if ! [[ $* = *-daemonize* ]] && ! [[ $* = *-daemonize* ]]; then
-    ARGS="$ARGS -serial stdio"
+# Provide rng device sourcing the hosts /dev/urandom and other standard parameters
+ARGS+=(-smp 2 -m 2048 -nodefaults -vga none -display none -no-reboot -watchdog-action poweroff -device virtio-rng-pci)
+
+if ! [[ $* == *-daemonize* ]] && ! [[ $* == *-daemonize* ]]; then
+    ARGS+=(-serial stdio)
+fi
+
+# virtual hardware watchdog not available on s390x
+if [[ $ARCH != "s390x" ]]; then
+    ARGS+=(-device i6300esb)
 fi
 
 KVERSION=${KVERSION-$(uname -r)}
 
 VMLINUZ="/lib/modules/${KVERSION}/vmlinuz"
+if ! [ -f "$VMLINUZ" ]; then
+    VMLINUZ="/lib/modules/${KVERSION}/vmlinux"
+fi
 
 if ! [ -f "$VMLINUZ" ]; then
-    [[ -f /etc/machine-id ]] && read MACHINE_ID < /etc/machine-id
+    [[ -f /etc/machine-id ]] && read -r MACHINE_ID < /etc/machine-id
 
-    if [[ $MACHINE_ID ]] && ( [[ -d /boot/${MACHINE_ID} ]] || [[ -L /boot/${MACHINE_ID} ]] ); then
+    if [[ $MACHINE_ID ]] && { [[ -d /boot/${MACHINE_ID} ]] || [[ -L /boot/${MACHINE_ID} ]]; }; then
         VMLINUZ="/boot/${MACHINE_ID}/$KVERSION/linux"
-    else
+    elif [ -f "/boot/vmlinuz-${KVERSION}" ]; then
         VMLINUZ="/boot/vmlinuz-${KVERSION}"
+    elif [ -f "/boot/vmlinux-${KVERSION}" ]; then
+        VMLINUZ="/boot/vmlinux-${KVERSION}"
+    elif [ -f "/boot/kernel-${KVERSION}" ]; then
+        VMLINUZ="/boot/kernel-${KVERSION}"
+    else
+        echo "Could not find a Linux kernel version $KVERSION to test with!" >&2
+        echo "Please install linux." >&2
+        exit 1
     fi
 fi
 
-exec $BIN $ARGS -kernel $VMLINUZ "$@"
+# only set -kernel if -initrd is specified
+if [[ $* == *-initrd* ]]; then
+    ARGS+=(-kernel "$VMLINUZ")
+fi
+
+echo "${0##*/}: $BIN ${ARGS[*]@Q} ${*@Q}"
+exec "$BIN" "${ARGS[@]}" "$@"
diff --git a/test/test-functions b/test/test-functions
--- a/test/test-functions
+++ b/test/test-functions
@@ -1,17 +1,53 @@
 #!/bin/bash
-PATH=/sbin:/bin:/usr/sbin:/usr/bin
+PATH=/usr/sbin:/usr/bin:/sbin:/bin
 export PATH
 
+# shellcheck disable=SC1090
 [[ -e .testdir${TEST_RUN_ID:+-$TEST_RUN_ID} ]] && . .testdir${TEST_RUN_ID:+-$TEST_RUN_ID}
-if [[ -z "$TESTDIR" ]] || [[ ! -d "$TESTDIR" ]]; then
+if [[ -z $TESTDIR ]] || [[ ! -d $TESTDIR ]]; then
     TESTDIR=$(mktemp -d -p "/var/tmp" -t dracut-test.XXXXXX)
 fi
 echo "TESTDIR=\"$TESTDIR\"" > .testdir${TEST_RUN_ID:+-$TEST_RUN_ID}
 export TESTDIR
 
-command -v test_check &>/dev/null || test_check() {
-        :
-    }
+KVERSION=${KVERSION-$(uname -r)}
+
+[ -z "$USE_NETWORK" ] && USE_NETWORK="network"
+
+if [[ -z $basedir ]]; then basedir="$(realpath ../..)"; fi
+
+DRACUT=${DRACUT-${basedir}/dracut.sh}
+PKGLIBDIR=${PKGLIBDIR-$basedir}
+
+TEST_KERNEL_CMDLINE+=" panic=1 oops=panic softlockup_panic=1 systemd.crash_reboot console=ttyS0,115200n81 $DEBUGFAIL "
+if [[ $V != "1" && $V != "2" ]]; then
+    TEST_KERNEL_CMDLINE+="quiet "
+fi
+
+test_dracut() {
+    TEST_DRACUT_ARGS+=" --local --no-hostonly --no-hostonly-cmdline --no-early-microcode --add test --force --kver $KVERSION"
+
+    # include $TESTDIR"/overlay if exists
+    if [ -d "$TESTDIR"/overlay ]; then
+        TEST_DRACUT_ARGS+=" --include $TESTDIR/overlay /"
+    fi
+
+    # shellcheck disable=SC2162
+    IFS=' ' read -a TEST_DRACUT_ARGS_ARRAY <<< "$TEST_DRACUT_ARGS"
+
+    "$DRACUT" \
+        --kernel-cmdline "rd.retry=10 rd.info rd.shell=0" \
+        "${TEST_DRACUT_ARGS_ARRAY[@]}" \
+        "$@" || return 1
+}
+
+command -v test_check &> /dev/null || test_check() {
+    :
+}
+
+command -v test_cleanup &> /dev/null || test_cleanup() {
+    :
+}
 
 # terminal sequence to set color to a 'success' color (currently: green)
 function SETCOLOR_SUCCESS() { echo -en '\033[0;32m'; }
@@ -27,65 +63,108 @@ COLOR_FAILURE='\033[0;31m'
 COLOR_WARNING='\033[0;33m'
 COLOR_NORMAL='\033[0;39m'
 
-check_root() {
-    if (( $EUID != 0 )); then
-        SETCOLOR_FAILURE; echo "Tests must be run as root! Please use 'sudo'."; SETCOLOR_NORMAL
-        exit 1
+# generate qemu arguments for named raw disks
+#
+# qemu_add_drive <index> <args> <filename> <id-name> [<bootindex>]
+#
+# index: name of the index variable (set to 0 at start)
+# args: name of the argument array variable (set to () at start)
+# filename: filename of the raw disk image
+# id-name: name of the disk in /dev/disk/by-id -> /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_$name
+# size: optional file size in MiB (0 implies size is not set)
+# bootindex: optional bootindex number
+#
+# to be used later with `qemu … "${args[@]}" …`
+# The <index> variable will be incremented each time the function is called.
+#
+# can't be easier than this :-/
+#
+# # EXAMPLES
+# ```
+#   declare -a disk_args=()
+#   declare -i disk_index=0
+#   qemu_add_drive disk_index disk_args "$TESTDIR"/root.ext3 root 0 1
+#   qemu_add_drive disk_index disk_args "$TESTDIR"/client.img client
+#   qemu_add_drive disk_index disk_args "$TESTDIR"/iscsidisk2.img iscsidisk2
+#   qemu_add_drive disk_index disk_args "$TESTDIR"/iscsidisk3.img iscsidisk3
+#   qemu "${disk_args[@]}"
+# ```
+qemu_add_drive() {
+    local index=${!1}
+    local file=$3
+    local name=${4:-$index}
+    local size=${5:-0}
+    local bootindex=$6
+
+    if [ "${size}" -ne 0 ]; then
+        dd if=/dev/zero of="${file}" bs=1MiB count="${size}" status=none
     fi
+
+    eval "${2}"'+=(' \
+        -device "virtio-scsi-pci,id=scsi${index}" \
+        -drive "if=none,format=raw,file=${file},id=drive-data${index}" \
+        -device "scsi-hd,bus=scsi${index}.0,drive=drive-data${index},id=data${index},${bootindex:+bootindex=$bootindex,}serial=${name}" \
+        ')'
+
+    # shellcheck disable=SC2219
+    let "${1}++"
+}
+
+test_marker_reset() {
+    dd if=/dev/zero of="$TESTDIR"/marker.img bs=1MiB count=1 status=none
+}
+
+test_marker_check() {
+    local marker=${1:-dracut-root-block-success}
+    local file=${2:-marker.img}
+
+    grep -U --binary-files=binary -F -m 1 -q "$marker" "$TESTDIR/$file"
+    return $?
 }
 
 while (($# > 0)); do
     case $1 in
         --run)
-            check_root
             echo "TEST RUN: $TEST_DESCRIPTION"
             test_check && test_run
-            exit $?;;
+            exit $?
+            ;;
         --setup)
-            check_root
             echo "TEST SETUP: $TEST_DESCRIPTION"
             test_check && test_setup
-            exit $?;;
+            exit $?
+            ;;
         --clean)
             echo "TEST CLEANUP: $TEST_DESCRIPTION"
             test_cleanup
             rm -fr -- "$TESTDIR"
             rm -f -- .testdir${TEST_RUN_ID:+-$TEST_RUN_ID}
-            exit $?;;
+            exit $?
+            ;;
         --all)
-            check_root
-            if ! test_check 2&>test${TEST_RUN_ID:+-$TEST_RUN_ID}.log ; then
-                echo -e "TEST: $TEST_DESCRIPTION " $COLOR_WARNING "[SKIPPED]" $COLOR_NORMAL
-                exit 0;
+            if ! test_check 2 &> test${TEST_RUN_ID:+-$TEST_RUN_ID}.log; then
+                echo -e "TEST: $TEST_DESCRIPTION " "$COLOR_WARNING" "[SKIPPED]" "$COLOR_NORMAL"
+                exit 0
             else
-                echo -e "TEST: $TEST_DESCRIPTION " $COLOR_SUCCESS "[STARTED]" $COLOR_NORMAL;
+                echo -e "TEST: $TEST_DESCRIPTION " "$COLOR_SUCCESS" "[STARTED]" "$COLOR_NORMAL"
             fi
-            if [[ "$V" == "1" ]]; then
+            if [[ $V == "1" || $V == "2" ]]; then
+                tee_command="tee"
+                if [[ $V == "2" && -x "$basedir/logtee" ]]; then
+                    tee_command="$basedir/logtee"
+                fi
                 set -o pipefail
                 (
                     test_setup && test_run
                     ret=$?
                     test_cleanup
-                    if ((ret!=0)) && [[ -f "$TESTDIR"/server.log ]]; then
+                    if ((ret != 0)) && [[ -f "$TESTDIR"/server.log ]]; then
                         mv "$TESTDIR"/server.log ./server${TEST_RUN_ID:+-$TEST_RUN_ID}.log
                     fi
                     rm -fr -- "$TESTDIR"
                     rm -f -- .testdir${TEST_RUN_ID:+-$TEST_RUN_ID}
                     exit $ret
-                ) </dev/null 2>&1 | tee test${TEST_RUN_ID:+-$TEST_RUN_ID}.log
-            elif [[ "$V" == "2" ]]; then
-                set -o pipefail
-                (
-                    test_setup && test_run
-                    ret=$?
-                    test_cleanup
-                    if ((ret!=0)) && [[ -f "$TESTDIR"/server.log ]]; then
-                        mv "$TESTDIR"/server.log ./server${TEST_RUN_ID:+-$TEST_RUN_ID}.log
-                    fi
-                    rm -fr -- "$TESTDIR"
-                    rm -f -- .testdir${TEST_RUN_ID:+-$TEST_RUN_ID}
-                    exit $ret
-                ) </dev/null 2>&1 | $basedir/logtee test${TEST_RUN_ID:+-$TEST_RUN_ID}.log
+                ) < /dev/null 2>&1 | "$tee_command" "test${TEST_RUN_ID:+-$TEST_RUN_ID}.log"
             else
                 (
                     test_setup && test_run
@@ -94,23 +173,24 @@ while (($# > 0)); do
                     rm -fr -- "$TESTDIR"
                     rm -f -- .testdir${TEST_RUN_ID:+-$TEST_RUN_ID}
                     exit $ret
-                ) </dev/null >test${TEST_RUN_ID:+-$TEST_RUN_ID}.log 2>&1
+                ) < /dev/null > test${TEST_RUN_ID:+-$TEST_RUN_ID}.log 2>&1
             fi
             ret=$?
             set +o pipefail
             if [ $ret -eq 0 ]; then
                 rm -- test${TEST_RUN_ID:+-$TEST_RUN_ID}.log
-                echo -e "TEST: $TEST_DESCRIPTION " $COLOR_SUCCESS "[OK]" $COLOR_NORMAL
+                echo -e "TEST: $TEST_DESCRIPTION " "$COLOR_SUCCESS" "[OK]" "$COLOR_NORMAL"
             else
-                echo -e "TEST: $TEST_DESCRIPTION " $COLOR_FAILURE "[FAILED]" $COLOR_NORMAL
+                echo -e "TEST: $TEST_DESCRIPTION " "$COLOR_FAILURE" "[FAILED]" "$COLOR_NORMAL"
                 if [ "$V" == "2" ]; then
-                    tail -c 1048576 $(pwd)/server${TEST_RUN_ID:+-$TEST_RUN_ID}.log $(pwd)/test${TEST_RUN_ID:+-$TEST_RUN_ID}.log
-                    echo -e "TEST: $TEST_DESCRIPTION " $COLOR_FAILURE "[FAILED]" $COLOR_NORMAL
+                    tail -c 1048576 "$(pwd)/server${TEST_RUN_ID:+-$TEST_RUN_ID}.log" "$(pwd)/test${TEST_RUN_ID:+-$TEST_RUN_ID}.log"
+                    echo -e "TEST: $TEST_DESCRIPTION " "$COLOR_FAILURE" "[FAILED]" "$COLOR_NORMAL"
                 else
                     echo "see $(pwd)/test${TEST_RUN_ID:+-$TEST_RUN_ID}.log"
                 fi
             fi
-            exit $ret;;
+            exit $ret
+            ;;
         *) break ;;
     esac
     shift
